[tool.poetry]
name = "study-lmm"
version = "0.1.0"
description = ""
authors = ["takutori <t.taichi.takutori.0214@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
